package com.midokter.app.repositary.model

import android.os.Parcelable
import java.io.Serializable

data class AppointmentResponse(
    val previous: Previous,
    val upcomming: Upcomming
): Serializable {
    data class Previous(
        val appointments: List<Appointment>,
        val created_at: String,
        val deleted_at: Any,
        val device_id: Any,
        val device_token: Any,
        val device_type: String,
        val email: String,
        val email_token: Any,
        val email_verified: Int,
        val email_verified_at: Any,
        val first_name: String,
        val id: Int,
        val last_name: String,
        val login_by: String,
        val other_id: Any,
        val otp: Int,
        val payment_mode: String,
        val phone: String,
        val rating: String,
        val regn_id: Any,
        val secondary_mobile: Any,
        val social_unique_id: Any,
        val updated_at: String,
        val wallet_balance: Int
    ): Serializable {
        data class Appointment(
            val appointment_type: String,
            val checkedout_at: Any,
            val checkin_at: Any,
            val consult_time: String,
            val created_at: String,
            val deleted_at: Any,
            val description: String,
            val doctor_id: Int,
            val doctor_reminder: Int,
            val engaged_at: Any,
            val hospital: Hospital,
            val id: Int,
            val patient_id: Int,
            val patient_reminder: Int,
            val report: Any,
            val scheduled_at: String,
            val service_id: Int,
            val status: String,
            val updated_at: String
        ) : Serializable {
            data class Hospital(
                val added_by: Any,
                val clinic: Clinic,
                val clinic_id: Int,
                val country_code: Any,
                val created_at: String,
                val deleted_at: Any,
                val email: String,
                val email_token: String,
                val email_verified: Int,
                val email_verified_at: Any,
                val first_name: String,
                val gender: String,
                val id: Int,
                val is_administrative: Int,
                val is_doctor: Int,
                val is_receptionist: Int,
                val is_staff: Int,
                val last_name: String,
                val medical_id: String,
                val mobile: String,
                val otp: Int,
                val regn_id: String,
                val role: Int,
                val services_id: Any,
                val specialities_name: Any,
                val tax_id: String,
                val updated_at: String
            ) : Serializable{
                data class Clinic(
                    val address: String,
                    val country_code: Any,
                    val created_at: String,
                    val deleted_at: Any,
                    val doctor_id: Int,
                    val email: String,
                    val id: Int,
                    val latitude: Double,
                    val longitude: Double,
                    val mobile: Any,
                    val name: String,
                    val phone: String,
                    val postal_code: String,
                    val updated_at: String
                ): Serializable
            }
        }
    }

    data class Upcomming(
        val appointments: List<Appointment>,
        val created_at: String,
        val deleted_at: Any,
        val device_id: Any,
        val device_token: Any,
        val device_type: String,
        val email: String,
        val email_token: Any,
        val email_verified: Int,
        val email_verified_at: Any,
        val first_name: String,
        val id: Int,
        val last_name: String,
        val login_by: String,
        val other_id: Any,
        val otp: Int,
        val payment_mode: String,
        val phone: String,
        val rating: String,
        val regn_id: Any,
        val secondary_mobile: Any,
        val social_unique_id: Any,
        val updated_at: String,
        val wallet_balance: Int
    ): Serializable {
        data class Appointment(
            val appointment_type: String,
            val checkedout_at: Any,
            val checkin_at: Any,
            val consult_time: String,
            val created_at: String,
            val deleted_at: Any,
            val description: String,
            val doctor_id: Int,
            val doctor_reminder: Int,
            val engaged_at: Any,
            val hospital: Hospital,
            val id: Int,
            val patient_id: Int,
            val patient_reminder: Int,
            val report: Any,
            val scheduled_at: String,
            val service_id: Int,
            val status: String,
            val updated_at: String
        ) : Serializable{
            data class Hospital(
                val added_by: Any,
                val clinic: Clinic,
                val clinic_id: Int,
                val country_code: Any,
                val created_at: String,
                val deleted_at: Any,
                val email: String,
                val email_token: String,
                val email_verified: Int,
                val email_verified_at: Any,
                val first_name: String,
                val gender: String,
                val id: Int,
                val is_administrative: Int,
                val is_doctor: Int,
                val is_receptionist: Int,
                val is_staff: Int,
                val last_name: String,
                val medical_id: String,
                val mobile: String,
                val otp: Int,
                val regn_id: String,
                val role: Int,
                val services_id: Any,
                val specialities_name: Any,
                val tax_id: String,
                val updated_at: String
            ) : Serializable{
                data class Clinic(
                    val address: String,
                    val country_code: Any,
                    val created_at: String,
                    val deleted_at: Any,
                    val doctor_id: Int,
                    val email: String,
                    val id: Int,
                    val latitude: Double,
                    val longitude: Double,
                    val mobile: Any,
                    val name: String,
                    val phone: String,
                    val postal_code: String,
                    val updated_at: String
                ): Serializable
            }
        }
    }
}